# fly.toml app configuration file generated for hex2025 on 2025-02-07T22:52:28Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hex2025'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '16gb'
  cpu_kind = 'shared'
  cpus = 8
